name: Deploy to Bunny.net Edge Scripting

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    name: "Upload script to Bunny Edge"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Script to Bunny Edge Scripting
        uses: BunnyWay/actions/deploy-script@main
        with:
          script_id: 85123
          file: "script.ts"
